language: node_js
node_js:
  - "14"

services:
  - mongodb

cache:
  directories:
    - "node_modules"

before_install:
  - npm config set progress false

install:
  - npm install

script:
  - npm test
